# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20161113_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='key',
            field=models.CharField(max_length=100, verbose_name='Chave'),
        ),
    ]
